FROM localhost/project-name:base-minimal

WORKDIR /root

ENV PS1="[\u@\h \W]# "

COPY project-name/Makefile Makefile

RUN apk add github-cli

RUN apk add ripgrep fd

RUN apk add neovim

RUN cd $HOME && \
    git clone --recursive --bare --depth=1 https://github.com/nnishant776/dotfiles $HOME/.dotfiles && \
    git --git-dir=$HOME/.dotfiles --work-tree=$HOME checkout main -- .bashrc .profile .local/share/bash && \
    rm -rf $HOME/.dotfiles

RUN cd $HOME && \
    rm -rf $HOME/.config/nvim && \
    git clone --recursive --depth=1 https://github.com/nnishant776/init.lua $HOME/.config/nvim

RUN go install "github.com/cweill/gotests/gotests@latest" && \
    go install "github.com/fatih/gomodifytags@latest" && \
    go install "github.com/josharian/impl@latest" && \
    go install "honnef.co/go/tools/cmd/staticcheck@latest" && \
    go install "golang.org/x/tools/gopls@latest" && \
    go install "github.com/segmentio/golines@latest" && \
    go install "golang.org/x/tools/cmd/goimports@latest" && \
    go install "go.uber.org/mock/mockgen@latest"

RUN env features=ide nvim --headless "+Lazy restore" "+qa"
