FROM localhost/project-name:base

WORKDIR /root

ENV PS1="[\u@\h \W]# "

COPY project-name/Makefile Makefile

RUN mkdir -p -m 755 /etc/apt/keyrings && \
    curl -G -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null && \
    chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg  && \
    echo "deb [arch=$(arch) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null && \
    apt-get -y update && \
    apt-get -y install gh

RUN cd ~ && \
    curl -G -L https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb -o ~/ripgrep_13.0.0_amd64.deb && \
    curl -G -L https://github.com/sharkdp/fd/releases/download/v8.7.0/fd-musl_8.7.0_amd64.deb -o ~/fd-musl_8.7.0_amd64.deb && \
    apt-get -y install ~/ripgrep_13.0.0_amd64.deb && \
    apt-get -y install ~/fd-musl_8.7.0_amd64.deb && \
    rm -rf ~/fd-musl_8.7.0_amd64.deb && \
    rm -rf ~/ripgrep_13.0.0_amd64.deb

RUN curl -G -L https://github.com/neovim/neovim/releases/download/stable/nvim-$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m).tar.gz -o ~/nvim.tar.gz && \
    mkdir -p ~/nvim && \
    tar -C ~/nvim --strip-components=1 -xf ~/nvim.tar.gz && \
    rm -rf ~/nvim/man && \
    cp -rf ~/nvim/* /usr/local/ && \
    rm -rf ~/nvim.tar.gz && \
    rm -rf ~/nvim

RUN cd ~ && \
    git clone --recursive --bare --depth=1 https://github.com/nnishant776/dotfiles $HOME/.dotfiles && \
    git --git-dir=$HOME/.dotfiles --work-tree=$HOME checkout main -- .bashrc .profile .local/share/bash && \
    rm -rf ~/.dotfiles

RUN cd ~ && \
    rm -rf ~/.config/nvim && \
    git clone --recursive --depth=1 https://github.com/nnishant776/init.lua ~/.config/nvim

RUN go install "github.com/cweill/gotests/gotests@latest" && \
    go install "github.com/fatih/gomodifytags@latest" && \
    go install "github.com/josharian/impl@latest" && \
    go install "honnef.co/go/tools/cmd/staticcheck@latest" && \
    go install "golang.org/x/tools/gopls@latest" && \
    go install "github.com/segmentio/golines@latest" && \
    go install "golang.org/x/tools/cmd/goimports@latest" && \
    go install "github.com/golang/mock/mockgen@latest"

RUN env features=ide nvim --headless "+Lazy restore" "+qa"
