FROM golang:latest as base

RUN apt -y update

RUN apt -y install --no-install-recommends \
    systemd \
    git \
    tree \
    curl \
    nano \
    python3-pip \
    python3-venv \
    unzip \
    tar \
    gzip \
    make \
    file \
    man-db \
    manpages-dev \
    build-essential

RUN apt -y clean all

ENV SHELL=/usr/bin/bash
