version: '3'
services:
  devcontainer:
    image: localhost/project-name:dev
    build:
      context: .
      dockerfile: project-name/Dockerfile
    cap_add:
    - SYS_PTRACE   # Add more capabilities based on the requirements
    container_name: container-prefix-container-name
    userns_mode: host
    privileged: false
    network_mode: host
    tty: true
    stdin_open: true
    working_dir: /workspace
    environment:
      SHELL: /bin/bash
      TZ: UTC
    security_opt:
    - label=disable
    - seccomp=unconfined
    volumes:
    - ../:/workspace
    - user-home:user-home
