all:

envcreate:
ifeq ($(editor), cli)
ifeq ($(infra), pod)
	$(MAKE) _setup_pod
else
	$(MAKE) _setup_compose
endif
else
	$(MAKE) _setup_vscode
endif

_validations:
ifeq ($(project_name), project-name)
	echo "Invalid configuration. Please provide a valid project name"
	exit 1
endif
ifeq ($(editor), cli)
ifeq ($(infra), pod)
ifeq ($(runtime), docker)
	echo "Invalid configuration. Docker doens't support local pods"
	exit 1
endif
endif
endif

Makefile: _makegen
	# sed -i "s/project-name/$(project_name)/g" .gitignore
	# sed -i '1,25d' Makefile
	# sed -i 's/devcontainer: gendevenv/devcontainer:/g' Makefile

_prebuild: _validations
ifeq ($(flavor), full)
	cp project-name/Dockerfile.full.base project-name/Dockerfile.base
	cp project-name/Dockerfile.full.dev project-name/Dockerfile.dev
	cp project-name/Makefile.full project-name/Makefile
else
	cp project-name/Dockerfile.minimal.base project-name/Dockerfile.base
	cp project-name/Dockerfile.minimal.dev project-name/Dockerfile.dev
	cp project-name/Makefile.minimal project-name/Makefile
endif
	rm -rf project-name/project-name
	mkdir -p project-name/project-name
	cp project-name/Makefile project-name/project-name/

	rm -rf $(project_name)
	cp -r project-name/ $(project_name)/
	mkdir -p $(project_name)/$(project_name)
	cp $(project_name)/Makefile $(project_name)/$(project_name)/

	cp devcontainer.template.json devcontainer.json
	cp docker-compose.template.yaml docker-compose.yaml
	cp pod.template.yaml pod.yaml

	$(shell find $(project_name) -type f -exec sed -i "s/project-name/$(project_name)/g" {} \;)

	sed -i "s/project-name/$(project_name)/g" docker-compose.yaml
	sed -i "s/project-name/$(project_name)/g" pod.yaml
	sed -i "s/project-name/$(project_name)/g" devcontainer.json
	sed -i "s/container-name/$(container_name)/g" devcontainer.json
	sed -i "s/container-name/$(container_name)/g" pod.yaml
	sed -i "s/container-name/$(container_name)/g" docker-compose.yaml

	cat $(project_name)/Dockerfile.base > $(project_name)/Dockerfile
	sed '1d' $(project_name)/Dockerfile.dev >> $(project_name)/Dockerfile

baseimage: _prebuild
ifeq ($(optimized), true)
ifeq ($(flavor), full)
	$(runtime) inspect localhost/project-name:full-base 2>&1 > /dev/null && \
	$(runtime) tag localhost/project-name:full-base localhost/$(project_name):base || \
	$(runtime) build -f project-name/Dockerfile.full.base -t localhost/project-name:full-base .
	$(runtime) build -f project-name/Dockerfile.full.dev -t localhost/project-name:full-dev .
else
	$(runtime) inspect localhost/project-name:minimal-base 2>&1 > /dev/null && \
	$(runtime) tag localhost/project-name:minimal-base localhost/$(project_name):base || \
	$(runtime) build -f project-name/Dockerfile.minimal.base -t localhost/project-name:minimal-base .
	$(runtime) build -f project-name/Dockerfile.minimal.dev -t localhost/project-name:minimal-dev .
endif
	$(runtime) build -f $(project_name)/Dockerfile.base -t localhost/$(project_name):base .
	$(runtime) build -f $(project_name)/Dockerfile.dev -t localhost/$(project_name):dev .
	rm -rf project-name/project-name
	rm -rf $(project_name)/$(project_name)
else
	$(runtime) build -f $(project_name)/Dockerfile -t localhost/$(project_name):dev .
endif

_setup_vscode: baseimage
	devcontainer up --docker-path $(runtime) --workspace-folder .. # Ensure that devcontainer cli is installed (sudo npm install -g @devcontainers/cli)

_setup_pod: baseimage
ifeq ($(runtime), podman)
	sed -i "s/$(project_name)\///g" $(project_name)/Dockerfile
	rm -rf project-name/project-name
	rm -rf $(project_name)/$(project_name)
	mkdir -p project-name/project-name
	cp $(project_name)/Makefile project-name/project-name/
	mkdir -p $(project_name)/$(project_name)
	cp $(project_name)/Makefile $(project_name)/$(project_name)/
	podman kube play --replace pod.yaml # Ensure that the podman cli is installed
	rm -rf project-name/project-name
	rm -rf $(project_name)/$(project_name)
else
	echo "Invalid runtime and infra combination"
	exit 1
endif

_setup_compose: baseimage
	$(runtime) compose up -d # Ensure that either of podman-compose or docker compose is installed

.PHONY: list
list:
	@LC_ALL=C $(MAKE) -pRrq -f $(firstword $(MAKEFILE_LIST)) : 2>/dev/null | \
	awk -v RS= -F: '/(^|\n)# Files(\n|$$)/,/(^|\n)# Finished Make data base/ {if ($$1 !~ "^[#.]") {print $$1}}' | \
   	sort | grep -E -v -e '^[^[:alnum:]]' -e '^$@$$'

envstart:
ifeq ($(editor), cli)
ifeq ($(infra), pod)
	podman pod start $(project_name)
else
	$(runtime) compose up -d
endif
else
	devcontainer up --docker-path $(runtime) --workspace-folder ..
endif

enventer: envstart
ifeq ($(editor), cli)
ifeq ($(infra), pod)
	podman exec -it -w /workspace $(project_name)-$(container_name) bash
else
	$(runtime) compose exec -w /workspace development bash
endif
else
	devcontainer open ..  # Ensure that vscode binary is discoverable in $PATH
endif

envstop:
ifeq ($(editor), cli)
ifeq ($(infra), pod)
	podman pod stop $(project_name)
else
	$(runtime) compose stop
endif
else
	$(runtime) stop vscode-$(container_name)
endif

envdestroy: envstop
ifeq ($(editor), cli)
ifeq ($(infra), pod)
	podman kube play --down pod.yaml
else
	$(runtime) compose down
endif
else
	$(runtime) container rm vscode-$(container_name)
endif

envpurge: envdestroy
ifeq ($(editor), cli)
	$(runtime) image rm localhost/$(project_name):dev
else
	# $(runtime) container rm vscode-$(container_name)
endif

envcleangen:
	rm -f project-name/Dockerfile.base
	rm -f project-name/Dockerfile.dev
	rm -f project-name/Makefile
	rm -rf project-name/project-name
	rm -rf $(project_name)
	rm -f devcontainer.json
	rm -f docker-compose.yaml
	rm -f pod.yaml
	rm -f Makefile

_makegen: _prebuild
	rm -f Makefile
	echo -e "all:" >> Makefile
	echo -e "\nenvcreate:" >> Makefile
ifeq ($(editor), cli)
ifeq ($(infra), pod)
	echo -e "\tmkdir -p $(project_name)/$(project_name)" >> Makefile
	echo -e "\tcp $(project_name)/Makefile $(project_name)/$(project_name)/" >> Makefile
	echo -e "\tpodman kube play --replace pod.yaml" >> Makefile
	echo -e "\trm -rf $(project_name)/$(project_name)" >> Makefile
else
	echo -e "\t$(runtime) compose build" >> Makefile
endif
else
	echo -e "\tdevcontainer build .." >> Makefile
endif
	echo -e "\nenvstart:" >> Makefile
ifeq ($(editor), cli)
ifeq ($(infra), pod)
	echo -e "\tpodman pod start $(project_name)" >> Makefile
else
	echo -e "\t$(runtime) compose up -d" >> Makefile
endif
else
	echo -e "\tdevcontainer up --docker-path $(runtime) --workspace-folder .." >> Makefile
endif
	echo -e "\nenventer: envstart" >> Makefile
ifeq ($(editor), cli)
ifeq ($(infra), pod)
	echo -e "\tpodman exec -it -w /workspace $(project_name)-$(container_name) bash" >> Makefile
else
	echo -e "\t$(runtime) compose exec -w /workspace development bash" >> Makefile
endif
else
	echo -e "\tdevcontainer open ..  # Ensure that vscode binary is discoverable in $PATH" >> Makefile
endif
	echo -e "\nenvstop:" >> Makefile
ifeq ($(editor), cli)
ifeq ($(infra), pod)
	echo -e "\tpodman pod stop $(project_name)" >> Makefile
else
	echo -e "\t$(runtime) compose stop" >> Makefile
endif
else
	echo -e "\t$(runtime) stop vscode-$(container_name)" >> Makefile
endif
	echo -e "\nenvdestroy: envstop" >> Makefile
ifeq ($(editor), cli)
ifeq ($(infra), pod)
	echo -e "\tpodman kube play --down pod.yaml" >> Makefile
else
	echo -e "\t$(runtime) compose down" >> Makefile
endif
else
	echo -e "\t$(runtime) container rm vscode-$(container_name)" >> Makefile
endif
	echo -e "\nenvpurge: envdestroy" >> Makefile
ifeq ($(editor), cli)
	echo -e "\t$(runtime) image rm localhost/$(project_name):dev"
else
	# $(runtime) container rm vscode-$(container_name)
endif
	echo -e "\nenvcleangen:" >> Makefile
	echo -e "\trm -f project-name/Dockerfile.base" >> Makefile
	echo -e "\trm -f project-name/Dockerfile.dev" >> Makefile
	echo -e "\trm -f project-name/Makefile" >> Makefile
	echo -e "\trm -rf project-name/project-name" >> Makefile
	echo -e "\trm -rf $(project_name)" >> Makefile
	echo -e "\trm -f devcontainer.json" >> Makefile
	echo -e "\trm -f docker-compose.yaml" >> Makefile
	echo -e "\trm -f pod.yaml" >> Makefile
	echo -e "\trm -f Makefile" >> Makefile

gendevenv: Makefile
