# Pod spec (to be used if you are using podman)
# podman kube play pod.yml
apiVersion: v1
kind: Pod
metadata:
  name: container-prefix
  namespace: project-name-dev
  labels:
    app: container-prefix
spec:
  containers:
  - name: container-name
    image: localhost/project-name:dev
    securityContext:
      privileged: false
      seLinuxOptions:
        type: spc_t
      capbilities:
        add: [SYS_PTRACE]             # Add more capabilities based on the requirements
      seccompProfile:
        type: Unconfined
      allowPrivilegeEscalation: false
    tty: true
    stdin: true
    workingDir: /workspace
    env:
    - name: SHELL
      value: /bin/bash
    - name: TZ
      value: UTC
    volumeMounts:
    - name: source_code
      mountPath: /workspace
    - name: user_home
      mountPath: user-home
  volumes:
  - name: source_code
    hostPath:
      path: ../
  - name: user_home
    hostPath:
      path: user-home
