# Pod spec (to be used if you are using podman)
# podman kube play pod.yml
apiVersion: v1
kind: Pod
metadata:
  name: project-name
  namespace: project-name-dev
  labels:
    app: project-name
spec:
  containers:
  - name: container-name
    image: localhost/project-name:dev
    securityContext:
      privileged: true
      capbilities:
        add: [SYS_PTRACE]       # Add more capabilities based on the requirements
      seccompProfile:
        type: Unconfined
      allowPrivilegeEscalation: true
    command: [/lib/systemd/systemd]       # Optional. Remove if you don't want systemd
    tty: true
    stdin: true
    workingDir: /workspace
    env:
      - name: SHELL
        value: /usr/bin/bash
      - name: TZ
        value: UTC
    volumeMounts:
    - name: source_code
      mountPath: /workspace
  volumes:
  - name: source_code
    hostPath:
      path: ../
